chore: test watchlist
consolelabs/mochi-api pull request #413
Opened 2022-10-04 06:34 UTC by catngh

**What does this PR do?**

-  Add tests for watchlist

2022-10-04 06:54 UTC, nguyennh4522 commented on pkg/handler/defi_test.go
> +			ctx.Request = httptest.NewRequest("POST", "/api/v1/defi/watchlist", bytes.NewBuffer(body))
add header `application/json` or change binding type to `BindJSON` or something like that

2022-10-04 07:27 UTC, nguyennh4522 commented
add test in entities layer

2022-10-04 13:33 UTC, nguyennh4522 commented on pkg/handler/testdata/user_watchlist/get-200-ok-pair.json
> +
don't keep empty file with no reason

2022-10-04 13:36 UTC, nguyennh4522 approved these changes

2022-10-05 02:17 UTC, trkhoi requested changes

2022-10-05 02:17 UTC, trkhoi commented on pkg/handler/defi.go
> +	if err := c.BindJSON(&req); err != nil {
chỗ này sao cần đổi em, trên prod a thấy vẫn xài được mà

2022-10-05 02:17 UTC, trkhoi commented on pkg/entities/defi_test.go
> +	cfg := config.Config{
use LoadTestConfig() in config

2022-10-05 03:04 UTC, catngh commented on pkg/handler/defi.go
> +	if err := c.BindJSON(&req); err != nil {
hàm Bind ko đọc dc body của test request nên phải chỉnh thành BindJSON, function như nhau a

2022-10-05 03:47 UTC, closed without merging