test: add test for telegram cmd
consolelabs/mochi-api pull request #421
Opened 2022-10-05 14:34 UTC by hoangharry

**What does this PR do?**

-   [x] add test for telegram command

2022-10-05 14:38 UTC, nguyennh4522 commented on pkg/handler/telegram.go
> +	fmt.Printf("LinkUserTelegramWithDiscord: %v\n", req)
remove log if it's not really necessary

2022-10-05 14:42 UTC, nguyennh4522 commented on pkg/handler/testdata/telegram/201-nil-data.json
> +}
you can reuse file 200-data-null.json

2022-10-05 15:26 UTC, trkhoi requested changes

2022-10-05 15:26 UTC, trkhoi commented on pkg/handler/telegram.go
> +	if req.DiscordID == "" || req.TelegramUsername == "" {
for post request, can edit `request.LinkUserTelegramWithDiscordRequest` to
```
type LinkUserTelegramWithDiscordRequest struct {
	TelegramUsername string `json:"telegram_username" form:"guild_id" binding:"required"`
	DiscordID        string `json:"discord_id" form:"guild_id" binding:"required"`
}
```
for validating and no need catch `req.DiscordID == ""`

2022-10-05 21:31 UTC, nguyennh4522 approved these changes

2022-10-06 01:59 UTC, trkhoi approved these changes

2022-10-06 02:45 UTC, merged