feat: sb remove conversation
consolelabs/mochi-api pull request #454
Opened 2022-10-19 11:57 UTC by hoangharry

**What does this PR do?**

-   [x] Sb remove conversation config

2022-10-19 12:30 UTC, trkhoi requested changes

2022-10-19 12:30 UTC, trkhoi commented on pkg/handler/configs.go
> +	if req.Emoji == "" || (req.Emoji == "" && req.EmojiStop == "") {
split this into another API to distinguish `message` and `conversation`, you can rename API if its name is meaningless
- `repostReactionGroup.POST("/start-stop", h.CreateConfigRepostReactionStartStop)` (existed)
- `repostReactionGroup.DELETE("/start-stop", h.CreateConfigRepostReactionStartStop)` (create new one)

2022-10-19 13:24 UTC, trkhoi approved these changes

2022-10-19 13:59 UTC, nguyennh4522 commented on pkg/handler/configs.go
> +	if req.Emoji == "" || (req.Emoji == "" && req.EmojiStop == "") {
how `(req.Emoji == "" && req.EmojiStop == "")` happen when the first condition failed (`req.Emoji != ""`)

2022-10-20 02:43 UTC, nguyennh4522 approved these changes

2022-10-20 03:23 UTC, merged