chore: update readme
consolelabs/mochi-api pull request #483
Opened 2022-11-02 09:40 UTC by catngh

**What does this PR do?**

- Update readme

2022-11-02 18:27 UTC, nguyennh4522 commented on README.MD
> +- `cmd/`
should have a description for `cmd`, this folder contains the main application entry point files for the project, with the directory name matching the name for the binary

2022-11-02 18:29 UTC, nguyennh4522 commented on README.MD
> +- `cmd/`
I think you should read about golang standard structure

2022-11-02 18:32 UTC, nguyennh4522 commented on README.MD
> +[Invite tracker](https://www.notion.so/Invite-tracker-40503e89ce40437c957f1eba1c87905d)
there should be a tab before the content in an item

2022-11-02 18:35 UTC, nguyennh4522 commented on README.MD
> +- [Core team members and Contributors](https://www.notion.so/3ab4b42bbc564e7b8d767521c25e78a0).
this is not public link

2022-11-03 02:31 UTC, trkhoi requested changes

2022-11-03 02:31 UTC, trkhoi commented on .env.sample
> +CENTRALIZED_WALLET_MNEMONIC='tag volcano eight thank tide danger coast health above argue embrace heavy'
use this
```CENTRALIZED_WALLET_PRIVATE_KEY='account metamask private IN_DISCORD_WALLET_MNEMONIC='metamask recovery phrase'```

2022-11-03 02:31 UTC, trkhoi commented on README.MD
> +   CENTRALIZED_WALLET_MNEMONIC=“your metamask wallet mnemonic”
CENTRALIZED_WALLET_PRIVATE_KEY

2022-11-03 03:45 UTC, trkhoi approved these changes

2022-11-03 03:58 UTC, nguyennh4522 commented on README.MD
> +- `cmd/` this folder contains the main application entry point files for the project,
remove `,`

2022-11-03 03:59 UTC, nguyennh4522 commented on README.MD
> +- `migrations/`
add description for `migrations`

2022-11-03 04:06 UTC, nguyennh4522 commented on README.MD
> +  - `config/`: `.env` file’s loader and reader
it's not just load and read `.env`. You should show what `config` is used for, not what it contains

2022-11-03 04:06 UTC, nguyennh4522 approved these changes

2022-11-03 04:10 UTC, nguyennh4522 commented on README.MD
> +   1. Create new API
its not match with ref

2022-11-03 06:27 UTC, merged