chore: dao voting channel api
consolelabs/mochi-api pull request #603
Opened 2022-12-29 08:40 UTC by catngh

**What does this PR do?**

- added `GET` and `DELETE` api for `guild_config_dao_proposal`
<img width="611" alt="Screenshot 2022-12-29 at 15 39 52" src="https://user-images.githubusercontent.com/84314071/209925860-89d7ccf0-af60-4a06-a8e7-996553a69feb.png">
<img width="491" alt="Screenshot 2022-12-29 at 15 40 48" src="https://user-images.githubusercontent.com/84314071/209925963-47592994-2e88-4abd-a20f-a870559499f7.png">

2022-12-29 09:01 UTC, trkhoi requested changes

2022-12-29 09:01 UTC, trkhoi commented on pkg/handler/config-channel/config.go
> +	var req request.DeleteGuildConfigDaoProposal
delete theo id giúp a với

2022-12-29 09:03 UTC, trkhoi requested changes

2022-12-29 09:03 UTC, trkhoi commented on pkg/handler/config-channel/config.go
> +func (h *Handler) GetGuildConfigDaoProposal(c *gin.Context) {
swagger

2022-12-30 03:06 UTC, haongo138 approved these changes

2022-12-30 04:52 UTC, trkhoi approved these changes

2022-12-30 06:37 UTC, merged