chore: implement price alert api
consolelabs/mochi-api pull request #679
Opened 2023-02-15 19:31 UTC by haongo138

**What does this PR do?**

-   [x] Implement Price alert API

**Media (Loom or gif)**

- Add new price alert:
<img width="728" alt="image" src="https://user-images.githubusercontent.com/27359472/219132523-3ed3a5d1-f866-434d-af6c-41dc5b35a84b.png">

- List my price alerts
<img width="736" alt="image" src="https://user-images.githubusercontent.com/27359472/219132977-425f9891-f082-443c-8171-55fb2c437753.png">

- Remove a price alert
<img width="732" alt="image" src="https://user-images.githubusercontent.com/27359472/219133110-28d34cd0-e570-4de1-ae4c-a5ea8382cfee.png">

2023-02-16 05:45 UTC, trkhoi approved these changes

2023-02-16 05:45 UTC, trkhoi commented on migrations/schemas/20230215141951-user_token_price_alerts.sql
> +
prepare migration database for flow send alert

2023-02-16 05:45 UTC, trkhoi requested changes
approve nhầm

2023-02-17 11:00 UTC, hoangharry commented on pkg/entities/defi.go
> +	rows, err := e.repo.UserTokenPriceAlert.Delete(req.UserID, req.CoincapID)
nếu chỉ remove alert dựa trên userId và coinId sẽ bị miss case user set 1 coin nhiều loại alert và nhiều price

2023-02-17 19:52 UTC, haongo138 commented on pkg/entities/defi.go
> +	rows, err := e.repo.UserTokenPriceAlert.Delete(req.UserID, req.CoincapID)
uki tui update lai rui nha

2023-02-20 03:08 UTC, trkhoi approved these changes

2023-02-20 03:38 UTC, hoangharry approved these changes

2023-02-20 03:39 UTC, merged