fix: discord webhook error
consolelabs/mochi-api pull request #845
Opened 2023-05-18 11:25 UTC by anhnh12

**What does this PR do?**
-   [x] Fix webhook 500 error: because some guilds were not created when Mochi Bot joined (maybe server was down at that time)
- [x] Remove guild_id fkey form guild_config_activities and guild_user_activity_logs

2023-05-18 11:39 UTC, trkhoi requested changes

2023-05-18 11:39 UTC, trkhoi commented on pkg/job/fetch_discord_users.go
> +	// fetch current guilds from discord rest API
remove cmt

2023-05-18 11:39 UTC, trkhoi commented on pkg/entities/guild.go
> +	_, err := e.repo.DiscordGuilds.GetByID(guildID)
chỗ này mình dùng hàm FirstOrCreate của gorm đc ko a

2023-05-18 11:39 UTC, trkhoi commented on pkg/entities/guild.go
> +	fmt.Println("e.discord.State.Guilds:", e.discord.State.Guilds)
remoev log

2023-05-18 12:24 UTC, anhnh12 commented on pkg/entities/guild.go
> +	_, err := e.repo.DiscordGuilds.GetByID(guildID)
k dc do k co san guild data

2023-05-18 12:55 UTC, vhbien000 approved these changes

2023-05-18 12:55 UTC, vhbien000 commented on pkg/entities/guild.go
> +		if !ok {
nhìn nó bằng phẳng hơn thôi chứ kcg
```suggestion
		if ok {
		   result = append(result, g)
		   continue 
		}
		bla bla
```

2023-05-18 12:55 UTC, vhbien000 commented on pkg/entities/guild.go
> +		if !ok || !dbGuild.Active {
giống bên trên
```suggestion
		if ok && dbGuild.Active {
		   result = append(result, dbGuild)
		   continue
		}
		
		err = e.CreateGuild(request.CreateGuildRequest{
			ID:       id,
			Name:     g.Name,
			JoinedAt: g.JoinedAt,
		})
		if err != nil {
			e.log.Fields(logger.Fields{"guildID": id}).Error(err, "[entity.FetchAndSyncGuilds] DeactivateGuild() failed")
			}
```

2023-05-18 12:55 UTC, vhbien000 commented on pkg/entities/webhook.go
> +	}
nitpick: line break

2023-05-18 12:55 UTC, vhbien000 commented on pkg/repo/discord_guilds/pg.go
> +	}
nitpick: line break

2023-05-19 05:21 UTC, trkhoi approved these changes

2023-05-19 05:27 UTC, merged